---
title: "earthquake_data"
format: html
---

# ESDA for Earthquake Data

Import the data.

```{r}
e_data <- read.csv("./usgs_earthquake_data_2000_2025.csv")
```

Now get the country of each entry,

```{r}
# Import libraries
library(sp)
library(rworldmap)
```

```{r}
# The single argument to this function, points, is a data.frame in which:
#   - column 1 contains the longitude in degrees
#   - column 2 contains the latitude in degrees
coords2country = function(points)
{  
  countriesSP <- getMap(resolution='low')
  #countriesSP <- getMap(resolution='high') #you could use high res map from rworldxtra if you were concerned about detail

  # convert our list of points to a SpatialPoints object

  # pointsSP = SpatialPoints(points, proj4string=CRS(" +proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +towgs84=0,0,0"))

  #setting CRS directly to that from rworldmap
  pointsSP = SpatialPoints(points, proj4string=CRS(proj4string(countriesSP)))  


  # use 'over' to get indices of the Polygons object containing each point 
  indices = over(pointsSP, countriesSP)

  # return the ADMIN names of each country
  indices$ADMIN
}
```

```{r}
# Give the coordinates to country names
coords2country(e_data[,c("longitude","latitude")]) 
```

```{r}
# Add the country names to the csv
e_data$country <- coords2country(e_data[,c("longitude","latitude")]) 
```

```{r}
library(tidyverse)
```

```{r}
library(sf)
library(lubridate)

japan_data <- e_data %>%
  filter(country == "Japan") %>%
  select(time, longitude, latitude, mag, depth) %>%
  st_as_sf(coords = c("longitude", "latitude"), crs=4326, remove=FALSE) %>%
  mutate(t_year = year(as.POSIXct(time)))
```

```{r}
source("./utils/mapper.R")
library(tmap)

tmap_mode("plot")
j_plot <- tm_shape(japan_data) +
  tm_dots(col="t_year",
          title.col="Year",
          palette="viridis",
          style="cont") +
  add_map_decorations()

j_plot
```

## Temporal EDA

```{r}
na.omit(japan_data)
```

```{r}
pairs_data <- japan_data[, sapply(japan_data, is.numeric)]

```

```{r}
# Create pairwise scatterplot
pairs(~longitude+latitude+mag+depth, data=japan_data,
      main="Scatterplot of Earthquake data")
```

```{r}
library(scatterplot3d)
library(plot3D)
library(rgl)
```

```{r}
scatter3D(x=japan_data$longitude, y=japan_data$depth, z=japan_data$mag)

```
